# Generated by Django 4.0.6 on 2022-11-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_app', '0006_friend_remove_usermodel_friends_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
